import { z } from 'zod';

/**
 * Owns the canonical UUID wire representation shared by every PSD EOC domain
 * module. IDs are generated by trusted application or database code and remain
 * stable for the lifetime of the referenced record.
 */
export const UuidSchema = z.string().uuid();

/** Canonical UUID value inferred from {@link UuidSchema}. */
export type Uuid = z.infer<typeof UuidSchema>;

/**
 * Owns the canonical absolute timestamp wire representation. Domain records
 * use immutable ISO 8601 strings at package boundaries rather than `Date`
 * objects, so REST, MCP, mobile, and persistence callers share one format.
 */
export const TimestampSchema = z.string().datetime({ offset: true });

/** Canonical timestamp value inferred from {@link TimestampSchema}. */
export type Timestamp = z.infer<typeof TimestampSchema>;

/**
 * Owns HTTPS-only transient links returned to clients for uploads, authorized
 * reads, and generated exports. Arbitrary URL schemes and plaintext HTTP are
 * rejected so a server result cannot become an executable or insecure link.
 */
export const HttpsUrlSchema = z
  .string()
  .url()
  .max(8_192)
  .refine(
    (value) => {
      try {
        return new URL(value).protocol === 'https:';
      } catch {
        return false;
      }
    },
    {
      message: 'Client-facing transient URLs must use HTTPS.',
    },
  );

/** HTTPS-only client link inferred from its schema. */
export type HttpsUrl = z.infer<typeof HttpsUrlSchema>;

/**
 * Owns positive, monotonically increasing version numbers used by immutable
 * roster, audience, and event-type revisions.
 */
export const VersionSchema = z.number().int().positive();

/** Canonical positive version inferred from {@link VersionSchema}. */
export type Version = z.infer<typeof VersionSchema>;

/** Returns true only when every string in a collection is unique. */
export function hasUniqueStrings(values: readonly string[]): boolean {
  return new Set(values).size === values.length;
}

/** Returns true when `later` is chronologically at or after `earlier`. */
export function isAtOrAfter(later: string, earlier: string): boolean {
  return Date.parse(later) >= Date.parse(earlier);
}
