import { createHash } from 'node:crypto';
import { existsSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { basename, dirname, resolve } from 'node:path';

const REPOSITORY_ROOT = new URL('..', import.meta.url).pathname;
const EXAMPLE_ENVIRONMENT_PATH = new URL('../.env.example', import.meta.url);
const LOCAL_ENVIRONMENT_PATHS = Object.freeze([
  new URL('../.env.local', import.meta.url),
  new URL('../packages/server/.env.local', import.meta.url),
] as const);
const GENERATED_ENVIRONMENT_MARKER =
  '# Generated by `bun run test:db:start`; synthetic values only.';
const EXPECTED_DATABASE_USERNAME = 'psd_eoc_test';
const EXPECTED_DATABASE_PASSWORD = 'synthetic_test_password';
const EXPECTED_DATABASE_NAME = 'psd_eoc_test';

type Environment = Readonly<Record<string, string | undefined>>;

function isDatabaseEnvironmentName(name: string): boolean {
  return name === 'TEST_DATABASE_URL' || name.startsWith('DATABASE_');
}

export type TestDatabaseCommand = 'start' | 'migrate' | 'seed' | 'web' | 'stop';

export function parseTestDatabaseCommand(
  arguments_: readonly string[],
): TestDatabaseCommand {
  const command = arguments_[0];
  if (
    arguments_.length !== 1 ||
    !['start', 'migrate', 'seed', 'web', 'stop'].includes(command ?? '')
  ) {
    throw new Error(
      'Usage: bun run test:db:{start|migrate|seed|stop} | bun run test:web',
    );
  }
  return command as TestDatabaseCommand;
}

export function testDatabaseProjectName(
  repositoryRoot: string = REPOSITORY_ROOT,
): string {
  const resolvedRoot = resolve(repositoryRoot);
  const worktree = basename(dirname(resolvedRoot))
    .toLowerCase()
    .replaceAll(/[^a-z0-9_-]/gu, '-');
  const digest = createHash('sha256')
    .update(resolvedRoot)
    .digest('hex')
    .slice(0, 8);
  return `${`psd-eoc-${worktree}`.slice(0, 54)}-${digest}`;
}

export function composeArguments(
  command: 'start' | 'stop',
  projectName: string = testDatabaseProjectName(),
): string[] {
  const common = [
    'compose',
    '--project-name',
    projectName,
    '-f',
    'compose.test.yml',
  ];
  return command === 'start'
    ? [...common, 'up', '-d', '--wait']
    : [...common, 'down', '--volumes'];
}

export function isGeneratedLocalEnvironment(
  contents: string | undefined,
): boolean {
  return contents?.startsWith(`${GENERATED_ENVIRONMENT_MARKER}\n`) ?? false;
}

export function generatedLocalEnvironment(
  example: string,
  databaseUrl: string,
): string {
  const names = new Set(['DATABASE_URL', 'TEST_DATABASE_URL']);
  const replaced = new Set<string>();
  const lines = example.split(/\r?\n/u).map((line) => {
    const separator = line.indexOf('=');
    const name = separator === -1 ? '' : line.slice(0, separator);
    if (!names.has(name)) return line;
    replaced.add(name);
    return `${name}=${databaseUrl}`;
  });
  if (replaced.size !== names.size) {
    throw new Error(
      '.env.example must define DATABASE_URL and TEST_DATABASE_URL.',
    );
  }
  return `${GENERATED_ENVIRONMENT_MARKER}\n${lines.join('\n').trimEnd()}\n`;
}

export function parseLocalEnvironment(
  contents: string,
): Record<string, string> {
  const environment: Record<string, string> = {};
  for (const line of contents.split(/\r?\n/u)) {
    if (line.length === 0 || line.startsWith('#')) continue;
    const separator = line.indexOf('=');
    if (separator <= 0) {
      throw new Error(
        'Generated local configuration contains an invalid line.',
      );
    }
    environment[line.slice(0, separator)] = line.slice(separator + 1);
  }
  return environment;
}

export function validatedGeneratedEnvironment(
  rootContents: string,
  serverContents: string,
): Record<string, string> {
  if (
    !isGeneratedLocalEnvironment(rootContents) ||
    !isGeneratedLocalEnvironment(serverContents) ||
    rootContents !== serverContents
  ) {
    throw new Error(
      'Synthetic database configuration is missing, unmanaged, or inconsistent.',
    );
  }

  const environment = parseLocalEnvironment(rootContents);
  const databaseUrl = environment.DATABASE_URL;
  if (
    environment.DATABASE_DRIVER !== 'postgres' ||
    databaseUrl === undefined ||
    databaseUrl !== environment.TEST_DATABASE_URL
  ) {
    throw new Error('Synthetic database configuration failed validation.');
  }

  let parsed: URL;
  try {
    parsed = new URL(databaseUrl);
  } catch {
    throw new Error('Synthetic database URL failed validation.');
  }
  if (
    parsed.protocol !== 'postgresql:' ||
    parsed.hostname !== '127.0.0.1' ||
    parsed.username !== EXPECTED_DATABASE_USERNAME ||
    parsed.password !== EXPECTED_DATABASE_PASSWORD ||
    parsed.pathname !== `/${EXPECTED_DATABASE_NAME}` ||
    !/^\d+$/u.test(parsed.port) ||
    parsed.search !== '' ||
    parsed.hash !== ''
  ) {
    throw new Error('Synthetic database URL failed validation.');
  }
  return environment;
}

export function conflictingAmbientDatabaseVariables(
  ambient: Environment,
  expected: Environment = {},
): string[] {
  return Object.keys(ambient)
    .filter(isDatabaseEnvironmentName)
    .filter((name) => {
      const value = ambient[name];
      return value !== undefined && value !== '' && value !== expected[name];
    })
    .sort();
}

export function pinnedSyntheticEnvironment(
  ambient: Environment,
  generated: Readonly<Record<string, string>>,
): Record<string, string> {
  const environment = Object.fromEntries(
    Object.entries(ambient).filter(
      (entry): entry is [string, string] => entry[1] !== undefined,
    ),
  );
  for (const name of Object.keys(environment)) {
    if (isDatabaseEnvironmentName(name)) delete environment[name];
  }
  delete environment.NODE_ENV;
  delete environment.BUN_ENV;
  return { ...environment, ...generated };
}

export async function withStartupRollback<T>(
  finalize: () => Promise<T>,
  rollback: () => Promise<void>,
): Promise<T> {
  try {
    return await finalize();
  } catch (error) {
    await rollback();
    throw error;
  }
}

function unmanagedLocalEnvironmentPaths(): URL[] {
  return LOCAL_ENVIRONMENT_PATHS.filter(
    (path) =>
      existsSync(path) &&
      !isGeneratedLocalEnvironment(readFileSync(path, 'utf8')),
  );
}

function writeLocalEnvironments(databaseUrl: string): void {
  const environment = generatedLocalEnvironment(
    readFileSync(EXAMPLE_ENVIRONMENT_PATH, 'utf8'),
    databaseUrl,
  );
  for (const path of LOCAL_ENVIRONMENT_PATHS) {
    writeFileSync(path, environment, { encoding: 'utf8', mode: 0o600 });
  }
}

function removeLocalEnvironments(): void {
  for (const path of LOCAL_ENVIRONMENT_PATHS) {
    if (
      existsSync(path) &&
      isGeneratedLocalEnvironment(readFileSync(path, 'utf8'))
    ) {
      unlinkSync(path);
    }
  }
}

function existingGeneratedEnvironment(): Record<string, string> | undefined {
  const existing = LOCAL_ENVIRONMENT_PATHS.filter((path) => existsSync(path));
  if (existing.length === 0) return undefined;
  if (existing.length !== LOCAL_ENVIRONMENT_PATHS.length) {
    throw new Error(
      'Synthetic database configuration is incomplete; run `bun run test:db:stop`.',
    );
  }
  return validatedGeneratedEnvironment(
    readFileSync(LOCAL_ENVIRONMENT_PATHS[0], 'utf8'),
    readFileSync(LOCAL_ENVIRONMENT_PATHS[1], 'utf8'),
  );
}

function requiredGeneratedEnvironment(): Record<string, string> {
  const environment = existingGeneratedEnvironment();
  if (environment === undefined) {
    throw new Error(
      'Synthetic database configuration is missing; run `bun run test:db:start`.',
    );
  }
  return environment;
}

async function runCompose(
  command: 'start' | 'stop',
  projectName: string,
): Promise<number> {
  const child = Bun.spawn(
    ['docker', ...composeArguments(command, projectName)],
    {
      cwd: REPOSITORY_ROOT,
      stderr: 'inherit',
      stdout: 'inherit',
    },
  );
  return child.exited;
}

async function rollbackStartedDatabase(projectName: string): Promise<void> {
  removeLocalEnvironments();
  if ((await runCompose('stop', projectName)) !== 0) {
    throw new Error('Synthetic database startup rollback failed.');
  }
}

async function runPinnedRepositoryCommand(
  command: 'migrate' | 'seed' | 'web',
): Promise<number> {
  let generated: Record<string, string>;
  try {
    generated = requiredGeneratedEnvironment();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
  const arguments_ =
    command === 'web'
      ? [
          process.execPath,
          'run',
          '--cwd',
          'packages/server',
          'dev',
          '--hostname',
          '127.0.0.1',
          '--port',
          '3000',
        ]
      : [process.execPath, 'run', '--cwd', 'packages/server', `db:${command}`];
  const child = Bun.spawn(arguments_, {
    cwd: REPOSITORY_ROOT,
    env: pinnedSyntheticEnvironment(process.env, generated),
    stderr: 'inherit',
    stdin: 'inherit',
    stdout: 'inherit',
  });
  const terminate = (): void => child.kill();
  process.once('SIGINT', terminate);
  process.once('SIGTERM', terminate);
  try {
    return await child.exited;
  } finally {
    process.off('SIGINT', terminate);
    process.off('SIGTERM', terminate);
  }
}

export async function runTestDatabaseCommand(
  command: TestDatabaseCommand,
): Promise<number> {
  if (command === 'migrate' || command === 'seed' || command === 'web') {
    return runPinnedRepositoryCommand(command);
  }

  const projectName = testDatabaseProjectName();
  if (command === 'stop') {
    const exitCode = await runCompose('stop', projectName);
    removeLocalEnvironments();
    return exitCode;
  }

  if (command === 'start') {
    const unmanaged = unmanagedLocalEnvironmentPaths();
    if (unmanaged.length > 0) {
      console.error(
        `Refusing to replace unmanaged local configuration: ${unmanaged.map((path) => path.pathname).join(', ')}`,
      );
      return 1;
    }
    let expected: Record<string, string> | undefined;
    try {
      expected = existingGeneratedEnvironment();
    } catch (error) {
      console.error(error instanceof Error ? error.message : String(error));
      return 1;
    }
    const conflicts = conflictingAmbientDatabaseVariables(
      process.env,
      expected,
    );
    if (conflicts.length > 0) {
      console.error(
        `Refusing to start with ambient database configuration: ${conflicts.join(', ')}. Unset it or use the existing generated values.`,
      );
      return 1;
    }
  }
  const exitCode = await runCompose('start', projectName);
  if (exitCode !== 0) return exitCode;

  try {
    await withStartupRollback(
      async () => {
        const portProcess = Bun.spawn(
          [
            'docker',
            'compose',
            '--project-name',
            projectName,
            '-f',
            'compose.test.yml',
            'port',
            'postgres',
            '5432',
          ],
          { cwd: REPOSITORY_ROOT, stderr: 'ignore', stdout: 'pipe' },
        );
        const [portOutput, portExitCode] = await Promise.all([
          new Response(portProcess.stdout).text(),
          portProcess.exited,
        ]);
        const match = /127\.0\.0\.1:(\d+)/u.exec(portOutput);
        if (portExitCode !== 0 || match?.[1] === undefined) {
          throw new Error('Docker did not report the PostgreSQL port.');
        }
        const testDatabaseUrl = `postgresql://${EXPECTED_DATABASE_USERNAME}:${EXPECTED_DATABASE_PASSWORD}@127.0.0.1:${match[1]}/${EXPECTED_DATABASE_NAME}`;
        writeLocalEnvironments(testDatabaseUrl);
        console.info(
          `Synthetic PostgreSQL is ready.\nWrote reserved configuration to .env.local and packages/server/.env.local.\nexport TEST_DATABASE_URL='${testDatabaseUrl}'\nexport DATABASE_URL="$TEST_DATABASE_URL"`,
        );
      },
      () => rollbackStartedDatabase(projectName),
    );
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    return 1;
  }
  return 0;
}

if (import.meta.main) {
  process.exitCode = await runTestDatabaseCommand(
    parseTestDatabaseCommand(Bun.argv.slice(2)),
  );
}
